version: '2'

networks:
  default:
    driver: overlay

services:

  node1:
    image: xemuliam/nifi
    ports:
      - 8080
    environment:
      IS_CLUSTER_NODE: 'cluster-node'
      ZK_NODES_LIST: 'node1,node-2,node_3'
      ZK_MYID: 1
      ZK_CLIENT_PORT: 2181

  node-2:
    image: xemuliam/nifi
    ports:
      - 8080
    environment:
      IS_CLUSTER_NODE: 'yes'
      ZK_NODES_LIST: 'node1 node-2 node_3'
      ZK_MYID: 2
      ZK_MONITOR_PORT: 2888

  node_3:
    image: xemuliam/nifi
    ports:
      - 8080
    environment:
      IS_CLUSTER_NODE: 'probably'
      ZK_NODES_LIST: 'node1, node-2 , ,   node_3'
      ZK_MYID: 3
      ZK_ELECTION_PORT: 3888
